server:
    port: ${SERVER_PORT}

spring:
    application:
        name: chuijun-server

    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${DDL_AUTO:update}
        properties:
            hibernate:
                show_sql: true
                format_sql: true

datagsm:
    oauth:
        client-id: ${DATAGSM_CLIENT_ID:}
        redirect-uri: ${DATAGSM_REDIRECT_URI:}
        authorization-base-url: ${DATAGSM_AUTHORIZATION_BASE_URL:https://oauth.authorization.datagsm.kr}
        resource-base-url: ${DATAGSM_RESOURCE_BASE_URL:https://oauth.resource.datagsm.kr}
        cookie-secure: ${DATAGSM_COOKIE_SECURE:false}

jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600
    refresh-token-expiration: 2592000
